In [25]:
import pandas as pd
import numpy as np

cols = ['col1', 'col2']

df = pd.DataFrame(columns= cols)

df1 = pd.DataFrame(data= [[10, 20], [30, 40]], index= range(2), columns= cols)

df2 = pd.DataFrame(data= [[50, 60], [70, 80]], index= range(2), columns= cols)

c1 = pd.concat([df, df1], axis= 0, ignore_index= True)
print(c1)

c2 = pd.concat([c1, df2], axis= 0, ignore_index= True)
print(c2)

a = np.array([20, 20, 30, 10, 30])
ret = np.unique(a, return_inverse= True, return_counts= True)
print(ret)
ret = np.unique(a, return_counts= True)
print(ret)

a = np.array([[10, 100, 1000], [20, 100, 1000], [10, 100, 1000], [30, 200, 2000], [30, 200, 2000]])
uni, uni_index, uni_count = np.unique(np.ravel_multi_index(a.T, a.max(0) + 1), return_inverse= True, return_counts= True)
print(uni, uni_index, uni_count)

print(uni_count[uni_index])

a = pd.DataFrame(data= [[1], [1], [15], [3], [2], [3], [2]], index= range(7), columns= ['col1'])
print(a[['col1']].var())

ret = c2[c2['col2'].isin([60, 70, 90])]
print(ret)

  col1 col2
0   10   20
1   30   40
  col1 col2
0   10   20
1   30   40
2   50   60
3   70   80
(array([10, 20, 30]), array([1, 1, 2, 0, 2]), array([1, 2, 2]))
(array([10, 20, 30]), array([1, 2, 2]))
[ 4223110  8245120 12468230] [0 1 0 2 2] [2 1 2]
[2 1 2 2 2]
col1    24.809524
dtype: float64
  col1 col2
2   50   60


In [23]:
[10, 20] + [30, 40]

[10, 20, 30, 40]